server:
  port: 8080
  # 웹 애플리케이션을 구분할 때 사용
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /
  # 예외 처리를 커스텀하게 진행하기 위해 Whitelabel Error Page 옵션 OFF
  error:
    whitelabel:
      enabled: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
#    url: jdbc:mariadb://localhost:3306/boilerplate?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    username: root
#    password: 1234
    url: ENC(ns8ZJzwYqaZM3TKZRQtbjfJIkeEtviPqlEh+J9WoHArGfeXZMBrbZMQLeXax2++VTA7c5LNSyRWxJi14aWUhmIQotdydkm3XQHbo97tMExwYPYGR9/RbFUNUXGPFoHHAk6hLeMnLHa/p8Lmyt+YCws01g+K8Aymj)
    username: ENC(NnrvtPzZhyKChaK4dfBf6Q==)
    password: ENC(kTzHrOGopiQ1NCz3YEmOhgKGAT3qfL2T)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true # 콘솔창에 sql 출력
    properties:
      hibernate:
        format_sql: true # 콘솔창에 출력되는 SQL문을 사람이 보기 편한 형태로 출력
        default_batch_fetch_size: 500 # 1:N 컬렉션 조회 시 성능 최적화
        highlight_sql: true
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정
  data:
    redis:
      host: ENC(X38V0Uuenrjv5QokELUtxWYjA/kRWgrb)
      port: 6379

cloud:
  aws:
    credentials:
      access-key: ENC(Sxlm237xzggApTkSKHN6njp7mEy2+RrdBy5larzLLWk=)
      secret-key: ENC(BBiradulat5gh14GUkz9QG1qkrZjb0UOx9vXj0MbO28dQTXsb8WB1KZ9xLLbxfANOxnhtc/0rOw=)
    s3:
      bucket: boilerplate-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 출력되는 SQL문에 ?가 아닌 조건에 바인딩 되는 값 및 조회 결과 출력
    org.hibernate.SQL: debug
    com.beboilerplate: debug

jwt:
  token-validity-in-seconds: 3600 # 1시간
  secret: gberliusbenrgliuhberslgiuhasberliughaliuerghlierusbglsiubrgluiehrsgliuhbearlgiubelsriugbleiurbgluewhrlirwleuih

jasypt:
  encryptor:
    bean: jasyptStringEncryptor